dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - docker build -t pitunes .
      - docker tag pitunes $DOCKERHUB_USERNAME/pitunes:test
      - docker push $DOCKERHUB_USERNAME/pitunes:test