pub const ALBUMS: &str = "Albums";
pub const ALL_TRACKS: &str = "All tracks";
pub const ARTISTS: &str = "Artists";
pub const ELLIPSIS: &str = "...";
pub const GENRES: &str = "Genres";
pub const GRAPHQL: &str = "api/graphql";
pub const PLAYLISTS: &str = "Playlists";
pub const TRACKS: &str = "Tracks";
pub const TRACKS_RESOURCE: &str = "api/tracks";
