[package]
name = "pitunes_server"
version = "0.1.0"
authors = ["Bernhard Fritz <bernhard.e.fritz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.2.1"
actix-multipart = "0.2.0"
actix-rt = "1.0.0"
actix-web = { version = "2.0.0", features = ["openssl"] }
actix-web-httpauth = "0.4.1"
base64 = "0.11.0"
chrono = { version = "0.4.10", features = ["serde"] }
clap = "2.33.0"
diesel = { version = "1.4.3", features = ["chrono", "r2d2", "sqlite"] }
diesel_migrations = "1.4.0"
futures = "0.3.1"
id3 = "0.3.0"
juniper = { version = "0.14.2", features = ["chrono"] }
lazy_static = "1.4.0"
mp3-duration = "0.1.10"
openssl = "0.10.28"
serde = "1.0.104"
serde_json = "1.0.44"
sha2 = "0.8.1"
tempfile = "3.1.0"
toml = "0.5.6"