CREATE TABLE IF NOT EXISTS "artist" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
    "guid" BLOB NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(16)))),
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"name"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "album" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
    "guid" BLOB NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(16)))),
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"name"	TEXT NOT NULL,
	"artist_id"	INTEGER,
	FOREIGN KEY("artist_id") REFERENCES "artist"("id") ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS "genre" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
    "guid" BLOB NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(16)))),
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"name"	TEXT NOT NULL
);
INSERT INTO "genre"("name") VALUES
    ('Blues'),
    ('Classic rock'),
    ('Country'),
    ('Dance'),
    ('Disco'),
    ('Funk'),
    ('Grunge'),
    ('Hip-Hop'),
    ('Jazz'),
    ('Metal'),
    ('New Age'),
    ('Oldies'),
    ('Other'),
    ('Pop'),
    ('Rhythm and Blues'),
    ('Rap'),
    ('Reggae'),
    ('Rock'),
    ('Techno'),
    ('Industrial'),
    ('Alternative'),
    ('Ska'),
    ('Death metal'),
    ('Pranks'),
    ('Soundtrack'),
    ('Euro-Techno'),
    ('Ambient'),
    ('Trip-Hop'),
    ('Vocal'),
    ('Jazz & Funk'),
    ('Fusion'),
    ('Trance'),
    ('Classical'),
    ('Instrumental'),
    ('Acid'),
    ('House'),
    ('Game'),
    ('Sound clip'),
    ('Gospel'),
    ('Noise'),
    ('Alternative Rock'),
    ('Bass'),
    ('Soul'),
    ('Punk'),
    ('Space'),
    ('Meditative'),
    ('Instrumental Pop'),
    ('Instrumental Rock'),
    ('Ethnic'),
    ('Gothic'),
    ('Darkwave'),
    ('Techno-Industrial'),
    ('Electronic'),
    ('Pop-Folk'),
    ('Eurodance'),
    ('Dream'),
    ('Southern Rock'),
    ('Comedy'),
    ('Cult'),
    ('Gangsta'),
    ('Top 40'),
    ('Christian Rap'),
    ('Pop/Funk'),
    ('Jungle'),
    ('Native US'),
    ('Cabaret'),
    ('New Wave'),
    ('Psychedelic'),
    ('Rave'),
    ('Show tunes'),
    ('Trailer'),
    ('Lo-Fi'),
    ('Tribal'),
    ('Acid Punk'),
    ('Acid Jazz'),
    ('Polka'),
    ('Retro'),
    ('Musical'),
    ('Rock ’n’ Roll'),
    ('Hard Rock'),
    ('Folk'),
    ('Folk-Rock'),
    ('National Folk'),
    ('Swing'),
    ('Fast Fusion'),
    ('Bebop'),
    ('Latin'),
    ('Revival'),
    ('Celtic'),
    ('Bluegrass'),
    ('Avantgarde'),
    ('Gothic Rock'),
    ('Progressive Rock'),
    ('Psychedelic Rock'),
    ('Symphonic Rock'),
    ('Slow rock'),
    ('Big Band'),
    ('Chorus'),
    ('Easy Listening'),
    ('Acoustic'),
    ('Humour'),
    ('Speech'),
    ('Chanson'),
    ('Opera'),
    ('Chamber music'),
    ('Sonata'),
    ('Symphony'),
    ('Booty bass'),
    ('Primus'),
    ('Porn groove'),
    ('Satire'),
    ('Slow jam'),
    ('Club'),
    ('Tango'),
    ('Samba'),
    ('Folklore'),
    ('Ballad'),
    ('Power ballad'),
    ('Rhythmic Soul'),
    ('Freestyle'),
    ('Duet'),
    ('Punk Rock'),
    ('Drum solo'),
    ('A cappella'),
    ('Euro-House'),
    ('Dance Hall'),
    ('Goa'),
    ('Drum & Bass'),
    ('Club-House'),
    ('Hardcore Techno'),
    ('Terror'),
    ('Indie'),
    ('BritPop'),
    ('Negerpunk'),
    ('Polsk Punk'),
    ('Beat'),
    ('Christian Gangsta Rap'),
    ('Heavy Metal'),
    ('Black Metal'),
    ('Crossover'),
    ('Contemporary Christian'),
    ('Christian rock'),
    ('Merengue'),
    ('Salsa'),
    ('Thrash Metal'),
    ('Anime'),
    ('Jpop'),
    ('Synthpop'),
    ('Abstract'),
    ('Art Rock'),
    ('Baroque'),
    ('Bhangra'),
    ('Big beat'),
    ('Breakbeat'),
    ('Chillout'),
    ('Downtempo'),
    ('Dub'),
    ('EBM'),
    ('Eclectic'),
    ('Electro'),
    ('Electroclash'),
    ('Emo'),
    ('Experimental'),
    ('Garage'),
    ('Global'),
    ('IDM'),
    ('Illbient'),
    ('Industro-Goth'),
    ('Jam Band'),
    ('Krautrock'),
    ('Leftfield'),
    ('Lounge'),
    ('Math Rock'),
    ('New Romantic'),
    ('Nu-Breakz'),
    ('Post-Punk'),
    ('Post-Rock'),
    ('Psytrance'),
    ('Shoegaze'),
    ('Space Rock'),
    ('Trop Rock'),
    ('World Music'),
    ('Neoclassical'),
    ('Audiobook'),
    ('Audio theatre'),
    ('Neue Deutsche Welle'),
    ('Podcast'),
    ('Indie-Rock'),
    ('G-Funk'),
    ('Dubstep'),
    ('Garage Rock'),
    ('Psybient');
CREATE TABLE IF NOT EXISTS "song" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
    "guid" BLOB NOT NULL UNIQUE DEFAULT (lower(hex(randomblob(16)))),
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"name"	TEXT NOT NULL,
	"duration"	INTEGER NOT NULL,
	"artist_id"	INTEGER,
	"album_id"	INTEGER,
	"genre_id"	INTEGER,
	"track_number"	INTEGER,
	FOREIGN KEY("artist_id") REFERENCES "artist"("id") ON UPDATE CASCADE ON DELETE SET NULL,
	FOREIGN KEY("album_id") REFERENCES "album"("id") ON UPDATE CASCADE ON DELETE SET NULL,
	FOREIGN KEY("genre_id") REFERENCES "genre"("id") ON UPDATE CASCADE ON DELETE SET NULL,
	UNIQUE("album_id","track_number")
);