[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
image = "bernhardfritz/cross:x86_64-unknown-linux-musl-0.2.1"

[target.arm-unknown-linux-musleabihf]
linker = "arm-linux-musleabihf-gcc"

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-musleabihf-gcc"