[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[target.arm-unknown-linux-musleabihf]
linker = "arm-linux-musleabihf-gcc"

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-musleabihf-gcc"