pub const ALBUMS: &str = "Albums";
pub const ALL_TRACKS: &str = "All tracks";
pub const ARTISTS: &str = "Artists";
pub const GENRES: &str = "Genres";
pub const GRAPHQL: &str = "graphql";
pub const PI_SYMBOL: &str = "π";
pub const PLAYLISTS: &str = "Playlists";
pub const STATIC: &str = "static";
pub const TRACKS: &str = "Tracks";
